import CustomReservation from "../models/CustomReservation.js";
import Package from "../models/Package.js";
import { createAdminNotification } from "../utils/adminNotificationHelper.js";

// CREATE RESERVATION REQUEST (User)
export const createReservation = async (req, res) => {
  try {
    const { budget, duration, interests, region, aiGeneratedPlan, estimatedPrice } = req.body;

    if (!budget || !duration || !interests || !region || !aiGeneratedPlan || !estimatedPrice) {
      return res.status(400).json({ message: "All reservation fields are required." });
    }

    const reservation = await CustomReservation.create({
      user: req.user._id,
      budget,
      duration,
      interests,
      region,
      aiGeneratedPlan,
      estimatedPrice,
      status: "Pending",
    });

    // Auto-create Admin Notification
    await createAdminNotification({
      title: "New Custom Tour Request 🗺️",
      message: `User ${req.user.name || "Customer"} requested a custom ${interests} tour for ${region} (Budget: ${budget}, Est: ₹${estimatedPrice}).`,
      type: "CUSTOM_RESERVATION",
      referenceId: reservation._id.toString(),
      actionUrl: "/admin/custom-requests",
    });

    return res.status(201).json({
      success: true,
      message: "Custom Tour Reservation requested successfully ✅",
      reservation,
    });
  } catch (error) {
    console.error("CREATE RESERVATION ERROR:", error);
    return res.status(500).json({ message: error.message });
  }
};

// GET USER RESERVATIONS (User)
export const getUserReservations = async (req, res) => {
  try {
    const reservations = await CustomReservation.find({ user: req.user._id })
      .populate("customPackage")
      .populate("booking")
      .sort({ createdAt: -1 });

    return res.status(200).json(reservations);
  } catch (error) {
    console.error("GET USER RESERVATIONS ERROR:", error);
    return res.status(500).json({ message: error.message });
  }
};

// GET RESERVATION BY ID
export const getReservationById = async (req, res) => {
  try {
    const reservation = await CustomReservation.findById(req.params.id)
      .populate("user", "name email")
      .populate("customPackage")
      .populate("booking");

    if (!reservation) {
      return res.status(404).json({ message: "Reservation not found." });
    }

    return res.status(200).json(reservation);
  } catch (error) {
    console.error("GET RESERVATION BY ID ERROR:", error);
    return res.status(500).json({ message: error.message });
  }
};

// GET ADMIN RESERVATIONS (Admin)
export const getAdminReservations = async (req, res) => {
  try {
    const reservations = await CustomReservation.find()
      .populate("user", "name email")
      .populate("customPackage")
      .populate("booking")
      .sort({ createdAt: -1 });

    return res.status(200).json(reservations);
  } catch (error) {
    console.error("GET ADMIN RESERVATIONS ERROR:", error);
    return res.status(500).json({ message: error.message });
  }
};

// UPDATE RESERVATION STATUS / MODIFY DETAILS (Admin)
export const updateReservationStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, adminRemarks, estimatedPrice, aiGeneratedPlan } = req.body;

    const reservation = await CustomReservation.findById(id);
    if (!reservation) {
      return res.status(404).json({ message: "Reservation not found." });
    }

    if (adminRemarks !== undefined) reservation.adminRemarks = adminRemarks;
    if (estimatedPrice !== undefined) reservation.estimatedPrice = estimatedPrice;
    if (aiGeneratedPlan !== undefined) reservation.aiGeneratedPlan = aiGeneratedPlan;
    if (status !== undefined) reservation.status = status;

    // If status changed to Approved, generate the Package document
    if (status === "Approved" && !reservation.customPackage) {
      const plan = reservation.aiGeneratedPlan;
      const customPkg = await Package.create({
        name: plan.name || `AI Custom: ${reservation.region} Tour`,
        description: plan.description || `Custom package generated by AI suggestion.`,
        price: reservation.estimatedPrice,
        duration: plan.duration || `${plan.itinerary?.length || 4} Days`,
        itinerary: plan.itinerary || [],
        region: reservation.region,
        isActive: false, // Keep out of public packages page
        isCustom: true,
      });

      reservation.customPackage = customPkg._id;
    }

    await reservation.save();

    return res.status(200).json({
      success: true,
      message: `Reservation request status updated to ${status} ✅`,
      reservation,
    });
  } catch (error) {
    console.error("UPDATE RESERVATION ERROR:", error);
    return res.status(500).json({ message: error.message });
  }
};
